import Navbar from "@/components/Navbar";
import ConvexClerkProvider from "@/components/providers/convexClerkProvider";
import { ThemeProvider } from "@/components/providers/themeProvider";
import localFont from "next/font/local";
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import "./globals.css";
import { RedirectToSignIn, SignedIn, SignedOut, SignIn } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { Button } from "@/components/ui/button";
import Homepage from "../components/homepage";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CoderView",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ConvexClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SignedIn>
              <div className="min-h-screen">
                <Navbar />
                <main className="px-4 sm:px-6 lg:px-8">{children}</main>
              </div>
            </SignedIn>

            <SignedOut>
              <Homepage />
            </SignedOut>
          </ThemeProvider>
          <Toaster />
        </body>
      </html>
    </ConvexClerkProvider>
  );
}
